config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :artists
    resources :categories
    resources :exhibitions
    resources :images
    resources :locations
    resources :nationalities
    resources :users
    resources :works
    root to: "artists#index"
  end

  root "main#index"
  get 'installation(/:idx)', to: 'main#installation',
                             defaults: { idx: 0 },
                             constraints: { idx: /\d+/ },
                             as: 'installation'

  resources :artists, only: [:index, :show] do
    get :autocomplete_artist_name, on: :collection
  end
  resources :contacts, only: [:new, :create]
  resources :exhibitions, only: :show

  get 'exhibitions/:exhibition_id/works(/:idx)', to: 'exhibitions/works#show',
                                                 defaults: { idx: 0 },
                                                 constraints: { idx: /\d+/ },
                                                 as: 'exhibition_works'

  resources :works, only: :show do
    collection do
      get :acquire
      get :featured
      get :recent
    end
  end

  get 'pages/about'
  get 'pages/contact'
  get 'pages/copyright'
  get 'pages/dmca'
  get 'pages/statistics'
  get 'pages/press'

  resources :contacts, only: [:new, :create]

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create", as: :do_login
  delete "/logout", to: "sessions#destroy", as: :logout
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :artist
  belongs_to :category
  belongs_to :location
  has_many :exhibition_works, dependent: :destroy
  has_many :exhibitions, through: :exhibition_works
  has_many :images, -> { order(:position) }, dependent: :destroy
  validates :location_id, :artist_id, :category_id, presence: true

  def tags=(tags_list)
    super(tags_list.split(',').map(&:strip).compact.reject(&:blank?))
  end

  filterrific(
    default_filter_params: { sorted_by: 'created_at desc' },
    available_filters: [
      :title,
      :with_location_id,
      :with_category_id,
      :with_artist_sort_name,
      :sorted_by,
      :search_query
    ]
  )

  scope :sorted_by, ->(sort) { order(sort) }
  scope :search_query, ->(term) { where('title ILIKE ?', "%#{term}%") }

  scope :featured_works, lambda {
    joins(:artist)
      .includes(:artist, :images)
      .where("(select count(id) from images where work_id=works.id) > 0
        and featured = true and published = true
        and artists.show_large_images = true")
  }

  scope :visible, -> { where(published: true) }

  scope :recently_updated, lambda {
    includes(:artist, :images)
      .where("(select count(id) from images where work_id=works.id) > 0
        and published = true")
      .order('updated_at DESC')
      .limit(20)
  }

  scope :recently_acquired, lambda {
    includes(:artist, :images)
      .where("(select count(id) from images where work_id=works.id) > 0
        and published = true
        and (extract(year from current_date) - acquisition_year) <= 1")
      .order('acquisition_year DESC, created_at DESC')
      .limit(20)
  }

  def self.csv_columns
    %w(id title artist_id work_year dimensions medium edition 
      acquisition_year description provenance price_paid
      private_notes missing_information location_id category_id
      keywords)
  end

  # for CSV export
  def textilize_without_paragraph(text)
    RedCloth.new(text || '', [:lite_mode]).to_html
  end

  def to_csv
    [id, title, artist.id, work_display_date || work_year,
     dimensions, medium, edition, acquisition_year,
     textilize(description),
     textilize_without_paragraph(provenance),
     price_paid, private_notes, missing_information,
     location.id, category.id, tags.join(',')
    ]
  end
end

app/controllers/admin/works_controller.rb
module Admin
  class WorksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Work.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Work.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/exhibitions/works_controller.rb
# rubocop:disable AbcSize
module Exhibitions
  class WorksController < ApplicationController
    def show
      @exhibition = Exhibition.find(params[:exhibition_id])
      works = @exhibition.works.includes(:artist).to_a
      idx = params[:idx].to_i
      @work = works[idx]
      @prev = (idx == 0) ? works.size - 1 : idx - 1
      @next = (idx + 1) % works.size
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def show
    @work = Work.includes(:artist).visible.find(params[:id])
    @additional_works = @work.artist.works.visible - [@work]
  end

  def acquire
    @work_rows = Work.recently_acquired.each_slice(4)
  end

  def recent
    @work_rows = Work.recently_updated.each_slice(4)
  end

  def featured
    @work_rows = Work.featured_works.order('artists.name').each_slice(4)
  end
end

app/views/works/_image_display.html.haml
.row
  - if exhibition
    = link_to(large_image_tag(image, alt_text(@work)), exhibition_works_path(@exhibition, @next))
  - else
    = large_image_tag(image, alt_text(@work))
  - unless image.caption.blank?
    %p=textilize_without_paragraph(image.caption)
  %br
  %br

app/views/works/_list.html.haml
- @work_rows.each do |row|
  .row.vertical-align
    - row.each do |work|
      .col-xs-12.col-sm-3
        .thumbnail
          = link_to(thumb_image_tag(work.images.first, alt_text(work)), work)
          .caption= work.artist.name

app/views/works/_thumb_display.html.haml
- if exhibition
  = link_to(thumb_image_tag(image, alt_text(@work)), exhibition_works_path(@exhibition, @next))
- else
  = thumb_image_tag(image, alt_text(@work))

app/views/works/acquire.html.haml
- title('Recently Acquired Works')

.row
  %h4.page-title Recently Acquired Works

= render 'list'

app/views/works/featured.html.haml
- title('Featured Works')

.row
  %h4.page-title Featured Works

= render 'list'

app/views/works/recent.html.haml
- title('Recently Updated Works')

.row
  %h4.page-title Recently Updated Works

= render 'list'

app/views/works/show.html.haml
- title(alt_text(@work))

.row
  .col-md-8
    = show_work_images
    - if @work.images.any? && !@work.artist.show_large_images
      %p.why
        %a{href: '#', id: 'why-small'}= "Why #{@work.images.count > 1 ? 'are these images' : 'is this image'} small?"
    %br
  .col-md-4
    %h5.title= @work.title
    = link_to(@work.artist.name, @work.artist)
    %br
    = work_date(@work)
    .work-details
      = show_work_info(:medium)
      = show_work_info(:dimensions)
      - if @work.edition.present?
        %p
          Edition:
          = @work.edition
    .work-details
      - if @work.provenance.present?
        Provenance: 
        = raw(textilize_without_paragraph(@work.provenance))
      - if @work.acquisition_year.present?
        %br
        Acquisition Year: #{@work.acquisition_year}
      %p
        Category:
        = @work.category.name
    - if @work.description.present?
      .work-details
        %h5 Description
        = raw(textilize(@work.description))
- if @additional_works.any?
  .row
    .col-md-12
      .other-works
        Other Works
  .row.vertical-align
    - @additional_works.each do |work|
      .col-xs-12
        .thumbnail
          = work_thumbnail(work)
          .caption= truncate(work.title)