config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :artists
    resources :categories
    resources :exhibitions
    resources :images
    resources :locations
    resources :nationalities
    resources :users
    resources :works
    root to: "artists#index"
  end

  root "main#index"
  get 'installation(/:idx)', to: 'main#installation',
                             defaults: { idx: 0 },
                             constraints: { idx: /\d+/ },
                             as: 'installation'

  resources :artists, only: [:index, :show] do
    get :autocomplete_artist_name, on: :collection
  end
  resources :contacts, only: [:new, :create]
  resources :exhibitions, only: :show

  get 'exhibitions/:exhibition_id/works(/:idx)', to: 'exhibitions/works#show',
                                                 defaults: { idx: 0 },
                                                 constraints: { idx: /\d+/ },
                                                 as: 'exhibition_works'

  resources :works, only: :show do
    collection do
      get :acquire
      get :featured
      get :recent
    end
  end

  get 'pages/about'
  get 'pages/contact'
  get 'pages/copyright'
  get 'pages/dmca'
  get 'pages/statistics'
  get 'pages/press'

  resources :contacts, only: [:new, :create]

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create", as: :do_login
  delete "/logout", to: "sessions#destroy", as: :logout
end

app/views/pages/about.html.haml
- title 'About'

.row
  %h4.page-title About

.row
  .col-md-8

    %h5.subtitle Barry Hoggard and James Wagner

    %p
      Barry Hoggard and James Wagner are small-scale but zealous patrons of all the arts, with particular devotion to the visual. They have served as members of boards attached to different non-profit institutions, have curated <a target="_blank" href="http://danglingbetween.com/">gallery</a> and online exhibitions, and have been invited, separately or together, to advise non-profit visual and performing arts institutions in the areas of their experiences.

    %h5 The Collection

    %p
      Hoggard and Wagner began collecting art as a couple in the mid 1990s, and some works were acquired by Wagner prior to their partnership. This web site is intended to publicize the collection and the artists within it. They have never sold a work of art from their collection and they do not intend to do so. Their hope is that this site will present it to a wider public than the relatively few people who are able to see it in a private home.

    %h5 Acknowledgments

    %p
      We would like to thank the interns who have helped us catalog our collection: Stephanie Korszen and Hannah Daly.

    %h5 Twitter

    = link_to 'HoggardWagner', 'https://twitter.com/hoggardwagner', target: '_blank'
    %br
    = link_to 'Barry', 'https://twitter.com/bhoggard', target: '_blank'
    %br
    = link_to 'James', 'https://twitter.com/wagnerblog', target: '_blank'

app/views/pages/contact.html.haml
- title 'Contact'

.row
  %h4.page-title Contact

.row
  .col-md-8

    Barry Hoggard and James Wagner
    %br
    255 West 23rd Street, Suite 2HE
    %br
    New York, NY 10011
    %br
    %br
    %p
      = link_to 'Contact Form', new_contact_path

app/views/pages/copyright.html.haml
- title 'Copyright'

.row
  %h4.page-title Copyright

.row
  .col-md-8

    %p Copyright &copy; 2008-#{Time.now.year} Barry Hoggard and James Wagner. Some rights reserved

    %p Copyright and other proprietary rights in material on this site may be held by individuals or entities other than or in addition to Barry Hoggard and James Wagner.

    %p If you believe that material posted on this site is infringing, please follow the procedures set forth in our #{link_to 'Digital Millennium Copyright Act Notice Policy', pages_dmca_path}, which is incorporated herein by reference.

    %p We are currently contacting artists for permission to display images of their works in our collection. If you can provide contact information for the artist or his/her estate, please #{link_to 'contact us', pages_contact_path}.

app/views/pages/dmca.html.haml
- title 'Digital Millennium Copyright Act Notice Policy'

.row
  %h4.page-title Digital Millennium Copyright Act Notice Policy

.row
  .col-md-8

    %p If you believe that material on this website infringes your copyright, you may notify us under the Digital Millennium Copyright Act ("DMCA"), 17 U.S.C. § 512(c)(3), by sending the following information in writing (by postal mail or fax) to our copyright agent (listed below):

    %ul
      %li Identify the copyrighted work claimed to be infringed. If multiple copyrighted works at a single online website are covered by a single notification, provide a representative list of such works at that website.
      %li Identify the material that you claim is infringing and that is to be removed, or access to which is to be disabled, and sufficiently describe its location on our website.
      %li Provide information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an e-mail address.
      %li Include a statement that you have a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.
      %li Include a statement that the information in the notification is accurate, and that, under penalty of perjury, you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
      %li Sign the document, either on your own behalf, or, if authorized, on behalf of the owner of an exclusive right that is allegedly infringed.
      

    %p 
      Barry Hoggard
      %br
      255 West 23rd Street, Suite 2HE
      %br
      New York, NY 10011
      %br
      phone: 917-519-1737
      %br
      fax: 212-994-9635

    %p If you fail to comply with all of the requirements, your DMCA notification might be invalid. Under the DMCA, we may respond to valid notifications by disabling access to or removing allegedly infringing material, terminating the accounts of repeated infringers, and making good-faith efforts to contact alleged infringers so that they might make appropriate counter-notifications.

    %p Before filing a notification, please carefully consider whether the use of copyrighted material at issue is protected by the "fair use" doctrine, as you could be liable for damages, including costs and attorney's fees, for a take-down notice if there is no infringing use.

    %p 
      %strong
        Counter-Notification

    %p If your material was removed (or made inaccessible), and you believe that it does not infringe, or that you have authorization for its use from the copyright owner, its agent, or the law, you may send a written counter-notification (by postal mail or fax) to our copyright agent, as follows:

    %ul
      %li Identify the material and its prior location on our website.
      %li Provide information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an e-mail address.
      %li Include a statement that you believe, under penalty of perjury, that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled.
      %li Include a statement that you consent to jurisdiction of the federal district court for the district where you reside (or of the Southern District of New York if you reside outside the United States), and that you will accept service of process from the person who provided notification under DMCA subsection (c)(1)(C), or an agent of such person.
      %li Sign the document.

    %p Under the DMCA, we may reinstate the material in response to a proper counter-notification. Please note that you could be liable for damages (including costs and attorney's fees) if you knowingly misrepresent that material is not infringing the copyrights of others.

app/views/pages/press.html.haml
- title 'Press'

.row
  %h4.page-title Press

.row
  .col-md-8
    %p
      = link_to 'Artspace interview', 'http://www.artspace.com/magazine/interviews_features/how_i_collect/how_i_collect_hoggard_and_wagner-51452'
      by Rachel Corbett, August 16, 2014
    %p
      = link_to 'Art F City interview', 'http://artfcity.com/2012/09/21/tonight-art-world-patron-saints-barry-hoggard-and-james-wagner-share-their-collection/'
      by Whitney Kimball, September 21, 2012
    %p
      = link_to 'Gangs of New York', 'http://www.brooklynrail.org/2007/7/artseen/brooklyn'
      by James Kalm, July 6, 2007

.row
  .col-md-8
    %br
    %br
    %p Video tour of exhibition at English Kills with artist Austin Thomas by James Kalm, October 16, 2012

    :plain
      <iframe width="640" height="360" src="https://www.youtube.com/embed/AnCWLrGsdHs?rel=0" frameborder="0" allowfullscreen></iframe>

app/views/pages/statistics.html.haml
- title 'Statistics'

.row
  %h4.page-title Statistics

  .col-md-6

    %table.table
      %tbody
        %tr
          %th Total Artists
          %td= number_with_delimiter(Artist.count)
        %tr
          %th Total Artworks
          %td= number_with_delimiter(Work.count)

    %p
      %b
        Note:
      These numbers do not describe the entire collection, but only those works added to the database to date.   The collectors currently estimate the total number of works to be in excess of one thousand.