config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :artists
    resources :categories
    resources :exhibitions
    resources :images
    resources :locations
    resources :nationalities
    resources :users
    resources :works
    root to: "artists#index"
  end

  root "main#index"
  get 'installation(/:idx)', to: 'main#installation',
                             defaults: { idx: 0 },
                             constraints: { idx: /\d+/ },
                             as: 'installation'

  resources :artists, only: [:index, :show] do
    get :autocomplete_artist_name, on: :collection
  end
  resources :contacts, only: [:new, :create]
  resources :exhibitions, only: :show

  get 'exhibitions/:exhibition_id/works(/:idx)', to: 'exhibitions/works#show',
                                                 defaults: { idx: 0 },
                                                 constraints: { idx: /\d+/ },
                                                 as: 'exhibition_works'

  resources :works, only: :show do
    collection do
      get :acquire
      get :featured
      get :recent
    end
  end

  get 'pages/about'
  get 'pages/contact'
  get 'pages/copyright'
  get 'pages/dmca'
  get 'pages/statistics'
  get 'pages/press'

  resources :contacts, only: [:new, :create]

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create", as: :do_login
  delete "/logout", to: "sessions#destroy", as: :logout
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.row
  %nav.navbar.navbar-default
    .container-fluid
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/"} Hoggard Wagner Collection
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li= link_to('artists', artists_path)
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              artworks
              %span.caret
            %ul.dropdown-menu
              %li= link_to('featured', featured_works_path)
              %li= link_to('recent acquisitions', acquire_works_path)
              %li= link_to('recent updates', recent_works_path)
              %li= link_to('installation views', installation_path)
              %li= link_to('2012 exhibition', exhibition_path(1))
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              about
              %span.caret
            %ul.dropdown-menu
              %li= link_to('about the collection', pages_about_path)
              %li= link_to('press', pages_press_path)
              %li= link_to('e-mail list subscribe', 'http://hoggardwagner.us1.list-manage.com/subscribe?u=bc6adecb3dfc7a869bd831856&id=76672cc07f', target: '_blank')
              %li= link_to('contact', pages_contact_path)
              %li= link_to('statistics', pages_statistics_path)
              %li= link_to('blog', 'http://hoggardwagner.tumblr.com/', target: '_blank')
              %li= link_to('copyright', pages_copyright_path)
          - if current_user
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                admin
                %span.caret
              %ul.dropdown-menu
                %li= link_to('artists', admin_artists_path)
                %li= link_to('artworks', admin_works_path)
                %li= link_to('nationalities', admin_nationalities_path)
            %li= link_to('logout', logout_path, method: :delete)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    %title Hoggard Wagner Collection | #{yield(:title) || 'Home'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag '/favicon.png'
    = yield :head
  %body
    .container
      .row
        = render partial: 'layouts/navigation'
    .container
      .row 
        = render partial: 'layouts/messages'
      = yield
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-167087-17', 'auto');
      ga('send', 'pageview');